# Generated by Django 2.1.8 on 2019-05-16 00:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('Movies', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='watch',
            field=models.ManyToManyField(blank=True, related_name='watched', to='accounts.CustomUser'),
        ),
    ]
